### Send POST request with json body
POST http://localhost:3001/auth/checkUserAccount
Content-Type: application/json

{
  "username": "testusername"
}

### Send POST request with body as parameters
POST http://localhost:3001/api/v1/notes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTk5Y2U4ZmFmMGVmMWEyOTc0M2E3ZGMiLCJ1c2VybmFtZSI6IjA5MDI1NDEzMzc5Iiwicm9sZSI6InVzZXIiLCJhY3RpdmUiOnRydWUsImlhdCI6MTcwNDU3ODg5MSwiZXhwIjoxNzA0NTgyNDkxfQ.xXw3OwRGzpi9XbTG2ikuj-GscelfyU0uHHyL4qoCMFg
Content-Type: application/json

{
  "title": "hello",
  "note": "123123"
}
